"""Verify a DPoP proof with Auth0's server-side Python verifier.

This helper is test-support only. It lets the Elixir test suite feed a proof
generated by ReqDPoP into an independently maintained Python resource-server
verifier without adding a runtime dependency to the package.
"""

import asyncio
import json
import sys
import warnings

warnings.filterwarnings("ignore")
from auth0_api_python import ApiClient
from auth0_api_python.config import ApiClientOptions


async def main() -> int:
    if len(sys.argv) > 1:
        with open(sys.argv[1], "r", encoding="utf-8") as f:
            data = json.load(f)
    else:
        data = json.load(sys.stdin)

    async def custom_fetch(url):
        if url.endswith("/.well-known/openid-configuration"):
            return {
                "issuer": data.get("issuer", "https://example.auth0.com/"),
                "jwks_uri": data.get("jwks_uri", "https://example.auth0.com/.well-known/jwks.json"),
            }

        if url == data.get("jwks_uri", "https://example.auth0.com/.well-known/jwks.json"):
            return {"keys": [data["jwk"]]}

        raise RuntimeError(f"unexpected fetch: {url}")

    client_opts = ApiClientOptions(
        domain=data.get("domain", "example.auth0.com"),
        audience=data.get("audience", "https://api.example.com"),
        custom_fetch=custom_fetch if "jwk" in data else None,
        dpop_enabled=True,
        dpop_required=True,
        dpop_iat_leeway=data.get("iat_leeway", 30),
        dpop_iat_offset=data.get("iat_offset", 300),
    )

    client = ApiClient(client_opts)

    if data.get("mode") == "verify_request":
        claims = await client.verify_request(
            headers={"authorization": data["authorization"], "dpop": data["proof"]},
            http_method=data["method"],
            http_url=data["url"],
        )
    else:
        claims = await client.verify_dpop_proof(
            access_token=data["access_token"],
            proof=data["proof"],
            http_method=data["method"],
            http_url=data["url"],
        )

    print(json.dumps({"ok": True, "claims": dict(claims)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(asyncio.run(main()))
    except Exception as exc:
        print(json.dumps({"ok": False, "error": str(exc)}), file=sys.stderr)
        raise
